baseURL = "https://bayisca.github.io/"
languageCode = 'en-us'
title = 'İsmail Can Anlaş'
theme = "PaperMod"

[params]
  defaultTheme = "auto"

  # 1. TARAYICI SEKMESİ İKONU (Favicon)
  [params.assets]
    favicon = "/logo.jpeg"
    favicon16x16 = "/logo.jpeg"
    favicon32x32 = "/logo.jpeg"

# 2. SOL ÜSTTEKİ İSİM YANI İKONU (Label Icon)
  [params.label]
    text = "İsmail Can"      # Logunun yanında yazacak isim
    icon = "/logo.jpeg"       # Logonun adresi
    iconHeight = 30          # Logonun boyutu 

  # --- GİRİŞ KARTI ---
  [params.homeInfoParams]
    Title = "Merhaba, Ben İsmail 👋"
    Content = "Python ve PyQt6 ile masaüstü uygulamaları geliştiriyorum. Projelerimi ve notlarımı burada paylaşıyorum."

  # --- SOSYAL MEDYA ---
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/bayisca"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/ismail-can-anla%C5%9F-270235242/"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:can2323fb@gmail.com"

  [params]
    googleAnalytics = G-NZRX6P5GXJ 