name: Hugo Site Check (CI)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Çek
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Temaların (PaperMod) inmesi için şart!

      - name: Hugo Kurulumu
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true # PaperMod bazen extended sürüm ister

      - name: Siteyi Derle
        run: hugo --gc --minify
